### ISSUE TITLE
谢谢作者, 很强帮助到了我, 但是有以下问题

### ISSUE THREAD

**Issue by stupid1t** [rwocj/wxpay-v3-spring-boot-starter#3]
1.尝试了下退款接口微信变了调用不同， 
2.其次使用过程中发现，代码再jdk1.8低版本在加密key太长有bug，升级jdk解决
3.native支付返回结果微信现在是个json，结构和代码写的不一样， 得单独处理下
4.其他的完美， okhttp用的出神入化， 厉害啊。 相比微信官方提供的sdk 狗屎，

所以万不得已自己拷贝了一份代码改了改.

**Comment by spinachomes** [comment]
好久没有做微信支付了，所以就停更了，能帮到你就好。哈哈

**Comment by spinachomes** [comment]
已发布0.6
